# Generated by Django 5.2.4 on 2025-07-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='preco',
            field=models.FloatField(),
        ),
    ]
