# Generated by Django 5.2.4 on 2025-07-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='qtd_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
